language: java
cache:
  npm: false
  
jdk:
  - openjdk8
dist: xenial
services:
  - docker

os: linux

env:
  - TERM=dumb

before_install:
  - sudo apt-get install nodejs
  - sudo wget https://services.gradle.org/distributions/gradle-6.3-bin.zip 
  - unzip -qq gradle-6.3-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.3
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

install:
  - npm install -g node@latest --force
  - node -v
  - npm -v
  - npm install -g @angular/cli

script:
  - gradle clean build test

deploy:
  - provider: script
    script: gradle pushDockerImage
    skip_cleanup: true
    on:
      branch: master

