language: java
jdk:
  - openjdk8
dist: xenial
services:
  - docker

env:
  - TERM=dumb

before_install:
  - sudo apt-get install nodejs

before_script:
  - npm install -g @angular/cli

script:
  - env TRAVIS=true gradle build

deploy:
  - provider: script
    script: gradle pushDockerImage
    skip_cleanup: true
    on:
      branch: master

