language: java
cache:
  npm: false
  
jdk:
  - openjdk8
dist: xenial
services:
  - docker

os: linux

env:
  - TERM=dumb

before_install:
  - sudo apt-get install nodejs
  - sdk install gradle 6.4.1
  - gradle -v

install:
  - npm install -g node@latest
  - node -v
  - npm -v
  - npm install -g @angular/cli

script:
  - gradle clean build test

deploy:
  - provider: script
    script: gradle pushDockerImage
    skip_cleanup: true
    on:
      branch: master

