services:
  nginx:
    container_name: nginx
    build: ./nginx/

    volumes:
      - static-content:/usr/src/app

  web:
    container_name: web
#    env_file: .env
    volumes:
      - scripts:/scripts
      - results:/results
#    environment:
#      - NODE_ENV=production
#
#    command: npm run package

volumes:
  scripts:
  results: